name: framework
description: This framework will help you to develop big apps by use Bloc.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Install rps package, if not already installed,
# 'dart pub global activate rps --version 0.7.0-dev.6'
#--------------- Example:-------------
### To create android dev build :
# "rps clean generator build android dev", or
# "rps android_apk"
### To create android prod bundle :
# "rps android_prod_bundle"
### To create ios ipa file :
# "rps ios_ipa"
### To clean, get dependencies and build dart code :
# "rps build"

scripts:
  clean:
    $before: flutter clean
    generator:
      $before: flutter pub get
      setup:
        dart run build_runner build --delete-conflicting-outputs
      build:
        $before: dart run build_runner build --delete-conflicting-outputs
        android:
          dev:
            $before: echo "Build runner success"
            $script: flutter build apk -t lib/main_dev.dart  --flavor=dev
            $after: echo "Apk Success"
        ios:
          dev:
            flutter build ipa -t lib/main_dev.dart  --flavor=dev
  android_apk: $clean generator build android dev
  ios_ipa: $clean generator build ios prod
  build: $clean generator setup

dependencies:
  auto_route: ^8.0.3
  cupertino_icons: 1.0.5
  device_info_plus: 9.1.0
  dropdown_search: 5.0.5
  easy_search_bar: 2.3.1
  equatable: 2.0.5
  file_picker: 5.3.2
  flash: 2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_datetime_picker_bdaya: 3.0.2
  flutter_html: 3.0.0-alpha.5
  flutter_inappwebview: 5.4.3+8
  flutter_jailbreak_detection: 1.10.0
  flutter_svg: 2.0.7
  fluttertoast: 8.1.2
  freezed_annotation: ^2.4.1
  geolocator: 9.0.2
  get_it: 7.6.0
  google_fonts: 5.1.0
  http: 1.1.0
  http_interceptor: 2.0.0-beta.7
  icons_plus: 4.0.0
  image_picker: 0.8.6
  injectable: ^2.4.1
  intl: 0.17.0
  json_serializable: 6.7.1
  mime_type: 1.0.0
  open_filex: 4.3.4
  open_settings: 2.0.2
  package_info_plus: 4.0.2
  permission_handler: 9.2.0
  shared_preferences: 2.0.8

dev_dependencies:
  analyzer: ^6.4.1
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.6.1
  json_annotation: 4.8.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/js/
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
